apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "private-gpt.fullname" . }}-conversation-api
  labels:
    {{- include "private-gpt.labels" . | nindent 4 }}
stringData:
  ACS_API_TOKEN: {{ .Values.ai.azure_content_safety.token | required "A value for .Values.ai.azure_content_safety.token is required" }}
