apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-gpt.fullname" . }}-conversation-ui
  labels:
    {{- include "private-gpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: conversation-ui
data:
  API_HOST: https://{{ .Values.ingress.host | quote | required "A value for .Values.ingress.host is required" }}/{{ include "private-gpt.fullname" . }}-conversation-api
  OIDC_AUDIENCE: {{ .Values.oidc.api_audience | quote | required "A value for .Values.oidc.api_audience is required" }}
  AZURE_APP_INSIGHTS_CONNECTION_STR: {{ .Values.monitoring.azure_app_insights.connection_str | quote | required "A value for .Values.monitoring.azure_app_insights.connection_str" }}
