apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-gpt.fullname" . }}-conversation-ui
  labels:
    {{- include "private-gpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: conversation-ui
data:
  default.conf: |
    server {
      client_max_body_size 0;
      listen 8080;
      server_name conversation-ui;
      server_tokens off;

      location = /health/liveness {
        return 204;
      }

      location / {
        ###
        # Use static files
        ###

        root /usr/share/nginx/html;
        try_files $uri /index.html;

        ###
        # Rewrite the API URL
        ###

        # Rewrite the API URL
        sub_filter 'http://127.0.0.1:8081' 'https://{{ .Values.ingress.host | required "A value for .Values.ingress.host is required" }}/{{ include "private-gpt.fullname" . }}-conversation-api';
        # Rewrite the UI URL
        sub_filter 'https://127.0.0.1:8080' 'https://{{ .Values.ingress.host | required "A value for .Values.ingress.host is required" }}';
        # Rewrite the OIDC authority
        sub_filter 'https://login.microsoftonline.com/common/v2.0' '{{ .Values.oidc.authority | required "A value for .Values.oidc.authority is required" }}';
        # Rewrite the OIDC API audience
        sub_filter 'e9d5f20f-7f14-4204-a9a2-0d91d6af5c82' '{{ .Values.oidc.api_audience | required "A value for .Values.oidc.api_audience is required" }}';
        # Rewrite the Azure App Insights connection string
        sub_filter 'InstrumentationKey=0b860d29-2a55-4d29-ab57-88cdd85a8da0;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com' '{{ .Values.appinsights.connection_str | required "A value for .Values.appinsights.connection_str" }}';
        # Rewrite recursively
        sub_filter_once off;
        # Rewrite every content type
        sub_filter_types *;

        ###
        # Cache static files
        ###

        location /assets/ {
          expires max;
          add_header Cache-Control "public";
        }
      }
    }
