apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-gpt.fullname" . }}-conversation-api
  labels:
    {{- include "private-gpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: conversation-api
spec:
  selector:
    matchLabels:
      {{- include "private-gpt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: conversation-api
  template:
    metadata:
      labels:
        {{- include "private-gpt.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: conversation-api
        azure.workload.identity/use: "true"
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/conversation-api-secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | required "A value for .Values.serviceAccountName is required" }}
      containers:
        - name: conversation-api
          image: "ghcr.io/clemlesne/private-gpt/conversation-api:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {{- toYaml .Values.resources | nindent 12 | required "A value for .Values.resources is required" }}
          livenessProbe:
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              path: /health/liveness
              port: http
          startupProbe:
            periodSeconds: 5
            failureThreshold: 30
            tcpSocket:
              port: http
          volumeMounts:
            - name: config
              mountPath: /app/config.toml
              subPath: config.toml
          env:
            - name: PG_ACS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "private-gpt.fullname" . }}-conversation-api
                  key: PG_ACS_API_TOKEN
      volumes:
        - name: config
          configMap:
            name: {{ include "private-gpt.fullname" . }}-conversation-api
