apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "private-gpt.fullname" . }}-conversation-api
  labels:
    {{- include "private-gpt.labels" . | nindent 4 }}
stringData:
  PG_ACS_API_TOKEN: {{ .Values.api.acs.token | required "A value for .Values.api.acs.token is required" }}
