apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-gpt.fullname" . }}-conversation-api
  labels:
    {{- include "private-gpt.labels" . | nindent 4 }}
    app.kubernetes.io/component: conversation-api
spec:
  selector:
    matchLabels:
      {{- include "private-gpt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: conversation-api
  template:
    metadata:
      labels:
        {{- include "private-gpt.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: conversation-api
        azure.workload.identity/use: "true"
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/conversation-api-secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | required "A value for .Values.serviceAccountName is required" }}
      containers:
        - name: conversation-api
          image: "ghcr.io/clemlesne/private-gpt/conversation-api:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {{- toYaml .Values.resources | nindent 12 | required "A value for .Values.resources is required" }}
          livenessProbe:
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              path: /health/liveness
              port: http
          readinessProbe:
            periodSeconds: 15
            timeoutSeconds: 5
            httpGet:
              path: /health/readiness
              port: http
          startupProbe:
            periodSeconds: 5
            failureThreshold: 30
            tcpSocket:
              port: http
          env:
            - name: MS_ROOT_PATH
              value: /{{ include "private-gpt.fullname" . }}-conversation-api
            - name: MS_ACS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "private-gpt.fullname" . }}-conversation-api
                  key: MS_ACS_API_TOKEN
            - name: MS_ACS_API_BASE
              value: "{{ .Values.api.acs.base | required "A value for .Values.api.acs.base is required" }}"
            - name: MS_LOGGING_APP_LEVEL
              value: {{ .Values.api.logging.app | required "A value for .Values.api.logging.app is required" }}
            - name: MS_LOGGING_SYS_LEVEL
              value: {{ .Values.api.logging.sys | required "A value for .Values.api.logging.sys is required" }}
            - name: MS_OAI_GPT_DEPLOY_ID
              value: {{ .Values.api.oai.gpt_deploy_id | required "A value for .Values.api.oai.gpt_deploy_id is required" }}
            - name: OPENAI_API_BASE
              value: "{{ .Values.api.oai.base | required "A value for .Values.api.oai.base is required" }}"
