image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

replicaCount: 2
nameOverride: ""
fullnameOverride: ""

# Requires to be binded with an Azure AD identity
# See: https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster
serviceAccountName: private-gpt-sa

ingress:
  # app.contoso.com
  host: null
  tls: {}

resources:
  requests:
    cpu: .25
    memory: 256Mi
  limits:
    cpu: .5
    memory: 512Mi

monitoring:
  logging:
    app: DEBUG
    sys: WARN
  azure_app_insights:
    connection_str: null

oidc:
  algorithms: []
  api_audience: null
  authority: null
  issuers: []
  jwks: null

ai:
  azure_content_safety:
    # https://[deployment].cognitiveservices.azure.com
    base: null
    token: null
  openai:
    ada_deployment: ada
    base: null
    gpt_deployment: gpt

tools:
  azure_form_recognizer:
    api_base: null
    api_token: null
  bing:
    search_url: null
    subscription_key: null
  tmdb:
    bearer_token: null
  news:
    api_key: null
  listen_notes:
    api_key: null
  open_weather_map:
    api_key: null
  google_places:
    api_key: null
  azure_cognitive_search:
    []
    # - api_key: xxx
    #   displayed_name: Légifrance
    #   index_name: legifrance-xml
    #   service_name: samples-v2
    #   top_k: 10
    #   usage: Useful when you need legal content contained in one of the codes (incl. civil, commercial, labor, electoral) derived from French legislation. Use this in priority for legal content in France.

persistence:
  cosmos:
    database: null
    url: null

redis:
  auth:
    enabled: false
  replica:
    replicaCount: 0
  resources:
    requests:
      cpu: .25
      memory: 256Mi
    limits:
      cpu: .5
      memory: 512Mi

qdrant:
  replicaCount: 2
  updateConfigurationOnChange: true
  persistence:
    size: 10Gi
    storageClassName: managed-csi
  resources:
    requests:
      cpu: .25
      memory: 256Mi
    limits:
      cpu: .5
      memory: 512Mi
