version: "2"
services:
  redis:
    image: docker.io/redis:7.2-alpine
    networks:
      - private-gpt
    ports:
      - 6379:6379
  qdrant:
    image: docker.io/qdrant/qdrant:v1.4.1
    networks:
      - private-gpt
    ports:
      - 6333:6333
    volumes:
      - qdrant-data:/qdrant/storage
networks:
  private-gpt:
    driver: bridge
volumes:
  qdrant-data: {}
